import { headers } from "next/headers";
import localFont from "next/font/local";
import "./globals.css";
import ContextProvider from "./context/wagmiProvider";
import { ToastContainer } from "react-toastify";
import { Bounce } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "BUFF CAT",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const headersList = await headers();
  const cookies =  headersList?.get("cookie") ?? "";

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ContextProvider cookies={cookies}>
          {children}
        </ContextProvider>
        <ToastContainer
        position="top-center"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick={false}
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="colored"
        transition={Bounce}
        />
      </body>
    </html>
  );
}
