import { headers } from "next/headers";
import localFont from "next/font/local";
import "./globals.css";
import ContextProvider from "./context/wagmiProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Buff OP_CAT",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const headersList = await headers();
  const cookies =  headersList?.get("cookie") ?? "";

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ContextProvider cookies={cookies}>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
