import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/header";
import ContextProvider from "./context/wagmiProvider";
import { headers } from "next/headers";
import Footer from "./components/Footer/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Buff OP_CAT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookies = headers().get("cookie");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="main-Bg">
          <ContextProvider cookies={cookies}>
            <Header />
            {children}
            <Footer/>
          </ContextProvider>
        </div>
      </body>
    </html>
  );
}
